In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df= pd.read_csv('medical_insurance.csv')
df

age     sex     bmi  children smoker     region      charges
0      19  female  27.900         0    yes  southwest  16884.92400
1      18    male  33.770         1     no  southeast   1725.55230
2      28    male  33.000         3     no  southeast   4449.46200
3      33    male  22.705         0     no  northwest  21984.47061
4      32    male  28.880         0     no  northwest   3866.85520
...   ...     ...     ...       ...    ...        ...          ...
2767   47  female  45.320         1     no  southeast   8569.86180
2768   21  female  34.600         0     no  southwest   2020.17700
2769   19    male  26.030         1    yes  northwest  16450.89470
2770   23    male  18.715         0     no  northwest  21595.38229
2771   54    male  31.600         0     no  southwest   9850.43200

[2772 rows x 7 columns]

In [ ]:
df.isnull().sum()

age         0
sex         0
bmi         0
children    0
smoker      0
region      0
charges     0
dtype: int64

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2772 entries, 0 to 2771
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   age       2772 non-null   int64  
 1   sex       2772 non-null   object 
 2   bmi       2772 non-null   float64
 3   children  2772 non-null   int64  
 4   smoker    2772 non-null   object 
 5   region    2772 non-null   object 
 6   charges   2772 non-null   float64
dtypes: float64(2), int64(2), object(3)
memory usage: 151.7+ KB


In [ ]:
df['sex'].unique()

array(['female', 'male'], dtype=object)

In [ ]:
df['smoker'].unique()

array(['yes', 'no'], dtype=object)

In [ ]:
df['region'].unique()

array(['southwest', 'southeast', 'northwest', 'northeast'], dtype=object)

In [ ]:
#Label Encoding for sex & smoking
from sklearn.preprocessing import LabelEncoder
le= LabelEncoder()
df['sex']= le.fit_transform(df['sex'])
df['smoker']= le.fit_transform(df['smoker'])

In [ ]:
#One Hot Encoding for Region
df= pd.get_dummies(df, columns=['region'])

In [ ]:
df

age  sex     bmi  children  smoker      charges  region_northeast  \
0      19    0  27.900         0       1  16884.92400             False   
1      18    1  33.770         1       0   1725.55230             False   
2      28    1  33.000         3       0   4449.46200             False   
3      33    1  22.705         0       0  21984.47061             False   
4      32    1  28.880         0       0   3866.85520             False   
...   ...  ...     ...       ...     ...          ...               ...   
2767   47    0  45.320         1       0   8569.86180             False   
2768   21    0  34.600         0       0   2020.17700             False   
2769   19    1  26.030         1       1  16450.89470             False   
2770   23    1  18.715         0       0  21595.38229             False   
2771   54    1  31.600         0       0   9850.43200             False   

      region_northwest  region_southeast  region_southwest  
0                False             False              True  
1                False              True             False  
2                False              True             False  
3                 True             False             False  
4                 True             False             False  
...                ...               ...               ...  
2767             False              True             False  
2768             False             False              True  
2769              True             False             False  
2770              True             False             False  
2771             False             False              True  

[2772 rows x 10 columns]

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2772 entries, 0 to 2771
Data columns (total 10 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   age               2772 non-null   int64  
 1   sex               2772 non-null   int64  
 2   bmi               2772 non-null   float64
 3   children          2772 non-null   int64  
 4   smoker            2772 non-null   int64  
 5   charges           2772 non-null   float64
 6   region_northeast  2772 non-null   bool   
 7   region_northwest  2772 non-null   bool   
 8   region_southeast  2772 non-null   bool   
 9   region_southwest  2772 non-null   bool   
dtypes: bool(4), float64(2), int64(4)
memory usage: 140.9 KB


In [ ]:
df.corr()

age       sex       bmi  children    smoker   charges  \
age               1.000000 -0.026046  0.113048  0.037574 -0.023286  0.298624   
sex              -0.026046  1.000000  0.042924  0.016020  0.082326  0.062837   
bmi               0.113048  0.042924  1.000000 -0.001492  0.011489  0.199846   
children          0.037574  0.016020 -0.001492  1.000000  0.006362  0.066442   
smoker           -0.023286  0.082326  0.011489  0.006362  1.000000  0.788783   
charges           0.298624  0.062837  0.199846  0.066442  0.788783  1.000000   
region_northeast  0.005290  0.000428 -0.140522 -0.022994  0.004468  0.009850   
region_northwest -0.001130 -0.018243 -0.142325  0.029541 -0.035902 -0.036874   
region_southeast -0.015242  0.021740  0.280058 -0.030504  0.072435  0.075652   
region_southwest  0.011708 -0.004912 -0.010913  0.025088 -0.044001 -0.051686   

                  region_northeast  region_northwest  region_southeast  \
age                       0.005290         -0.001130         -0.015242   
sex                       0.000428         -0.018243          0.021740   
bmi                      -0.140522         -0.142325          0.280058   
children                 -0.022994          0.029541         -0.030504   
smoker                    0.004468         -0.035902          0.072435   
charges                   0.009850         -0.036874          0.075652   
region_northeast          1.000000         -0.313119         -0.344754   
region_northwest         -0.313119          1.000000         -0.346815   
region_southeast         -0.344754         -0.346815          1.000000   
region_southwest         -0.319318         -0.321227         -0.353681   

                  region_southwest  
age                       0.011708  
sex                      -0.004912  
bmi                      -0.010913  
children                  0.025088  
smoker                   -0.044001  
charges                  -0.051686  
region_northeast         -0.319318  
region_northwest         -0.321227  
region_southeast         -0.353681  
region_southwest          1.000000

In [ ]:
X= df.drop('charges', axis=1).values
X

array([[19, 0, 27.9, ..., False, False, True],
       [18, 1, 33.77, ..., False, True, False],
       [28, 1, 33.0, ..., False, True, False],
       ...,
       [19, 1, 26.03, ..., True, False, False],
       [23, 1, 18.715, ..., True, False, False],
       [54, 1, 31.6, ..., False, False, True]], dtype=object)

In [ ]:
y= df['charges'].values
y

array([16884.924  ,  1725.5523 ,  4449.462  , ..., 16450.8947 ,
       21595.38229,  9850.432  ])

In [ ]:
#Feature Scaling
from sklearn.preprocessing import StandardScaler
sc= StandardScaler()
X= sc.fit_transform(X)

sc_y= StandardScaler()
y= y.reshape(len(y), 1)
y= sc.fit_transform(y)

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test= train_test_split(X, y, test_size=0.3, random_state=0)

In [ ]:
X_train

array([[ 0.9155768 , -1.01453565, -0.88137188, ..., -0.56124016,
         1.61827036, -0.57235147],
       [ 0.27632319, -1.01453565,  0.30328766, ..., -0.56124016,
         1.61827036, -0.57235147],
       [ 1.76791496, -1.01453565,  0.18335312, ..., -0.56124016,
        -0.61794372, -0.57235147],
       ...,
       [ 1.41277406, -1.01453565,  0.27636358, ..., -0.56124016,
        -0.61794372, -0.57235147],
       [ 0.06323865,  0.98567261, -0.93522004, ..., -0.56124016,
         1.61827036, -0.57235147],
       [ 1.34174588, -1.01453565, -0.40571313, ...,  1.78176845,
        -0.61794372, -0.57235147]])

In [ ]:
y_train

array([[ 0.93880216],
       [ 2.27826168],
       [ 0.23109569],
       ...,
       [ 0.1094081 ],
       [-0.54881431],
       [-0.08535434]])

##Multiple Linear Regression

In [ ]:
from sklearn.linear_model import LinearRegression
lr= LinearRegression()
lr.fit(X_train, y_train)

LinearRegression()

In [ ]:
y_predict= lr.predict(X_test)

In [ ]:
from sklearn.metrics import r2_score
r2_score(y_test, y_predict)

0.7703038663585713

##Polynomial Multiple Linear Regression

In [ ]:
from sklearn.linear_model import LinearRegression
lr= LinearRegression()
lr.fit(X, y)

LinearRegression()

In [ ]:
from sklearn.preprocessing import PolynomialFeatures
poly= PolynomialFeatures(degree=4)
X_poly= poly.fit_transform(X)

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test= train_test_split(X, y, test_size=0.3, random_state=0)

In [ ]:
lr2= LinearRegression()
lr2.fit(X_poly, y)

LinearRegression()

In [ ]:
lr2.fit(X_train, y_train)

LinearRegression()

In [ ]:
y_predict= lr2.predict(X_test)

In [ ]:
from sklearn.metrics import r2_score
r2_score(y_test , y_predict)

0.7703038663585713

##SVR

In [ ]:
#Feature Scaling
from sklearn.preprocessing import StandardScaler
sc= StandardScaler()
X= sc.fit_transform(X)

sc_y= StandardScaler()
y= y.reshape(len(y), 1)
y= sc.fit_transform(y)

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test= train_test_split(X, y, test_size=0.2, random_state=0)

In [ ]:
from sklearn.svm import SVR
svr= SVR(kernel= 'rbf')
svr.fit(X, y)

/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:1183: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVR()

In [ ]:
y_predict= svr.predict(X)

In [ ]:
from sklearn.metrics import r2_score
r2_score(y_predict, y)

0.8295209357671167

##Decision Tree Regression

In [ ]:
from sklearn.tree import DecisionTreeRegressor
dt= DecisionTreeRegressor(random_state=0)
dt.fit(X, y)

DecisionTreeRegressor(random_state=0)

In [ ]:
from sklearn.metrics import r2_score
y_predict= dt.predict(X)
r2_score(y_predict, y)

0.9987210035288099

##Random Forest Regression

In [ ]:
from sklearn.ensemble import RandomForestRegressor
rf= RandomForestRegressor(n_estimators=10, random_state=0)
rf.fit(X, y)

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:1152: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)


RandomForestRegressor(n_estimators=10, random_state=0)

In [ ]:
from sklearn.metrics import r2_score
y_predict= rf.predict(X)
r2_score(y_predict, y)

0.9933263363075947

In [ ]:
models= {
    'Mutiple Linear Regression': 0.7703038663585713,
    'Polynomial Regression': 0.7703038663585713,
    'SVR': 0.8295209357671167,
    'Decision Tree Regression': 0.9987210035288099,
    'Random Forest Regression': 0.9933263363075947
}

In [ ]:
models = pd.Series(models)
models

Mutiple Linear Regression    0.770304
Polynomial Regression        0.770304
SVR                          0.829521
Decision Tree Regression     0.998721
Random Forest Regression     0.993326
dtype: float64